### ISSUE TITLE
Implementação do padrão State (Pedidos.java)

### ISSUE THREAD

**Issue by imagal** [luiscrjr/sysAdega#1]
Implementação do padrão State com 3 ou mais estados.
Incluir inicialmente: Aberto, Fechado, Em Andamento.
Talvez incluir: Cancelado, Em espera.

**Comment by imagal** [comment]
State implementado.
Tentei fazer da forma mais prática, mais fácil de ler, mas eu não gostei da forma que ficou.
O maior problema é conseguir persistir o "estado" no banco de dados. 
Eu preferi persistir o "estadoPedido" e usar esse atributo para poder escolher qual é o estado atual correto.
Existem outras formas com Enums, mas ficaria muito mais complexo de ler e mais demorado pra debuggar.

Se todos concordarem com a implementação, podemos fechar este issue.
Porém agora precisamos pensar em quais os métodos podemos implementar nesses estados.

**Comment by leticiabac** [comment]
De acordo com persistir somente a String "estadoPedido"!
