### ISSUE TITLE
Criar relacionamento Many to many para pedidos

### ISSUE THREAD

**Issue by luiscrjr** [luiscrjr/sysAdega#10]

**Comment by leticiabac** [comment]
Sem entrar na questão do hibernate, para que um pedido tenha mais de um vinho não será necessária uma nova tabela? Algo como <**idPedido, idVinho**, qtdeVinho>?
Uma nova tabela implicaria em uma nova classe.. talvez ItemDePedido?
Ou existe alguma outra forma sem criação de outra tabela?
