### ISSUE TITLE
entregar o trabalho!

### ISSUE THREAD

**Issue by andrePfeiffer** [luiscrjr/sysAdega#15]
Arquivo .war do projeto web (não esquecer de exportar o código fonte);
Listar no corpo do e-mail os integrantes do grupo.
A data de entrega do trabalho é até o dia 15/11/17 às 23h59.

**Comment by leticiabac** [comment]
Segue email da Tatiana com o que devemos entregar.

> Pessoal,
> 
> como vocês já sabem, vocês precisarão entregar um trabalho em grupo que valerá 40% da nota de RTP.
> 
> O arquivo Trabalho Prático Vinhos – Parte II (Pedidos).docx do site contém um resumo do que ainda precisa ser implementado, utilizando como base o projeto dos vinhos que fizemos nas aulas de laboratório.
> 
> Apesar do trabalho ser entregue em grupo, é fundamental que cada aluno saiba implementá-lo individualmente. É isso que se espera da disciplina de RTP.
> 
> Basicamente, o que ainda precisa ser feito é:
> 
>     Implementar o CRUD de clientes;
>     Implementar a criação de pedidos;
>     Adicionar mais estados para o pedido e implementar o padrão State.
> 
> Pede-se também a implementação de mais uma funcionalidade adicional para o SisAdega, a escolha do grupo! Sejam criativos!
> 
> O trabalho deve ser enviado por e-mail contendo os arquivos:
> 
>     Arquivo .war do projeto web (não esquecer de exportar o código fonte);
>     Arquivo .sql com o script de criação do BD (deve-se obrigatoriamente utilizar um BD SQLite externo ao projeto) + arquivo .db do banco de dados criado;
>     Arquivo texto contendo um "relatório" da implementação das funcionalidades pedidas (como fizeram cada um dos pontos acima, visão geral do código fonte do trabalho, explicação de como "instalar" a aplicação e quais arquivos precisam ser alterados, como por exemplo, o local que indica o caminho do banco de dados, e o que mais vocês acharem relevante) - não tem um template específico, mas sejam caprichosos!
> 
> A data de entrega do trabalho é até o dia 15/11/17 às 23h59. Listar no corpo do e-mail os integrantes do grupo.
> 
> Abs,
> 
> Tatiana

**Comment by luiscrjr** [comment]
Feito!
