### ISSUE TITLE
Limpeza do código (Refactoring)

### ISSUE THREAD

**Issue by imagal** [luiscrjr/sysAdega#18]
Galera, no Pull Request #17 eu modifiquei um pouco o código que a professora mandou pra gente.
A intenção foi de remover todos os erros e warnings do Eclipse para ficarmos só com os TODOs em vista.

Dentre as demais modificações menores, eu adicionei verificações em casts (exemplo: https://github.com/luiscrjr/sysAdega/blob/1c0382b5b60c11a6a1ecd89141a2fce16f52697b/src/bebidas/dao/PedidoDAO.java#L30-L43 )

Me avisem se o código está todo ok para podermos fechar este Issue!

**Comment by luiscrjr** [comment]
Igor, eu testei aqui e parece funcionar bem. Posso fechar esse issue?
