### ISSUE TITLE
Métodos para o State (iteration 2)

### ISSUE THREAD

**Issue by imagal** [luiscrjr/sysAdega#20]
Temos o Padrão State implementado.
Todos os pedidos são divididos por estado e conseguimos modificar o estado do pedido em run time.
Mas agora a questão é, que métodos esse estado deve manter?

Até agora não temos nada que vá dar algum beneficio imediato por estamos usando o Padrão State.
Preciso de ideias :)

**Comment by leticiabac** [comment]
Implementei apenas os métodos mínimos necessários para alternar entre os estados existentes: Aberto, Em andamento, Encerrado e Cancelado.

Fiquei em dúvida sobre que ação transformaria um pedido "Aberto" em "Em andamento"... 
Apenas para testar, chamei de "prepararPedido", mas aceito sugestões melhores!

Favor testar mudanças de estado no "Consultar Pedido Por Estado".

![image](https://user-images.githubusercontent.com/13417163/33237024-58d12ab0-d24e-11e7-937c-e34dbc70d3a6.png)

![image](https://user-images.githubusercontent.com/13417163/33237027-6ad95afc-d24e-11e7-875f-1d9b80589978.png)

**Comment by leticiabac** [comment]
Atualizando a imagem dos estados para tirar a observação sobre as quantidades.

![image](https://user-images.githubusercontent.com/13417163/33460461-5647b9f6-d615-11e7-9098-dd944ed69935.png)
