### ISSUE TITLE
Alterar o BD para diretório relativo do projeto.

### ISSUE THREAD

**Issue by luiscrjr** [luiscrjr/sysAdega#3]
Alterar o BD para diretório relativo do projeto.

**Comment by imagal** [comment]
Adicionado código de teste no bebidas.dao.HibernateUtil.java, mencionado do Pull Request #17.
Existem algumas maneiras de modificar dinamicamente o url do jdbc no persistence, o código de teste demonstra uma das mais fáceis.

O problema é que não há um path direto para o diretório do projeto, não encontrei uma forma fácil de apontar pro adega.db3 que vem junto com o código do Git.
O máximo que conseguimos é ir para o workspace do eclipse, no momento.
O persistence em si aponta para a pasta padrão do Tomcat (${catalina_base}) que é uma pasta gerada pelo servidor em um arquivo .bat do próprio Tomcat.
