### ISSUE TITLE
Fazer o CRUD de clientes

### ISSUE THREAD

**Issue by andrePfeiffer** [luiscrjr/sysAdega#4]
Fazer o CRUD Completo de clientes usando o CRUD de vinhos como base
![crud clientes](https://user-images.githubusercontent.com/788888/32420065-1d8658b4-c26c-11e7-9b08-56929b95dada.png)

**Comment by luiscrjr** [comment]
Pessoal, só para fins informativos, na tela de cadastro dos clientes criei os campos que julguei necessários (nome, cpf, cep, endereço, numero, complemento, bairro, cidade, estado e país). Como melhoria, vocês vão observar que o campo cpf já tem máscara própria e script validador de cpf. Além disso, não é necessário preencher o endereço completo - basta digitar o cep e trocar de campo, que os outros campos (não incluídos número e complemento) serão preenchidos automaticamente baseado no resultado do webservice dos correios.

**Comment by luiscrjr** [comment]
Acabei o crud de clientes, peço ajuda de vocês para validarem e eu poder fechar o issue.
