### ISSUE TITLE
permitir adicionar mais de um vinho no mesmo pedido

### ISSUE THREAD

**Issue by andrePfeiffer** [luiscrjr/sysAdega#7]
Permitir a seleção de mais de um vinho por pedido, cada um com sua quantidade.

**Comment by luiscrjr** [comment]
Criada a parte do JSP para vincular vários vinhos ao mesmo pedido.

**Comment by leticiabac** [comment]
Sugiro reabrir esta issue, pois falta tratar a passagem desta informação para o servlet e o model.

**Comment by leticiabac** [comment]
Possibilidade para ler todos os valores de campos com mesmo name:

```
String[] arrayIdVinho = request.getParameterValues("vinho");
String[] arrayQtdVinho = request.getParameterValues("qtdVinho");
```
