### ISSUE TITLE
Fazer os tratamentos de erros no CriarPedidoManager.java

### ISSUE THREAD

**Issue by andrePfeiffer** [luiscrjr/sysAdega#8]
Fazer os tratamentos de erros no CriarPedidoManager.java

**Comment by leticiabac** [comment]
Inseri algumas verificações:

- se há pelo menos um vinho no pedido
- Qtde de de cada vinho >0
- se há estoque suficiente

Além disso incluí try/catch para inserir o pedido e os itens de pedido no banco.
